import os
import time
from typing import Any, Dict, List, Optional, Tuple

import requests


BASE_URL = "https://api.brightdata.com"


class BrightDataClient:
    """Client for Bright Data collector and self-healing APIs."""

    def __init__(self) -> None:
        self.token = os.getenv("BRIGHT_DATA_API_TOKEN")
        self.collector = os.getenv("BRIGHT_DATA_COLLECTOR_ID")

        if not self.token:
            raise RuntimeError(
                "BRIGHT_DATA_API_TOKEN is not set. "
                "Add it to Streamlit Secrets or your .env file."
            )

        if not self.collector:
            raise RuntimeError(
                "BRIGHT_DATA_COLLECTOR_ID is not set. "
                "Add it to Streamlit Secrets or your .env file."
            )

    @property
    def headers(self) -> Dict[str, str]:
        """Return authentication headers for Bright Data."""

        return {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

    def trigger(self, inputs: List[Dict[str, Any]]) -> str:
        """
        Start a Bright Data collector run.

        Returns:
            Bright Data collection/snapshot ID.
        """

        response = requests.post(
            f"{BASE_URL}/dca/trigger",
            params={
                "collector": self.collector,
                "queue_next": 1,
            },
            headers=self.headers,
            json=inputs,
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = response.text

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data trigger error "
                f"{response.status_code}: {result}"
            )

        if not isinstance(result, dict):
            raise RuntimeError(
                f"Unexpected Bright Data trigger response: {result}"
            )

        collection_id = result.get("collection_id")

        if not collection_id:
            # Some Bright Data responses may use snapshot_id.
            collection_id = result.get("snapshot_id")

        if not collection_id:
            raise RuntimeError(
                f"Bright Data did not return collection_id "
                f"or snapshot_id: {result}"
            )

        return str(collection_id)

    def dataset(
        self,
        snapshot_id: str,
    ) -> Optional[List[Dict[str, Any]]]:
        """
        Get the dataset generated by a collector run.

        Returns:
            List of records when ready.
            None when the collection is still running.

        Raises:
            RuntimeError when Bright Data reports a real failure
            or an unexpected response.
        """

        response = requests.get(
            f"{BASE_URL}/dca/dataset",
            params={
                "id": snapshot_id,
            },
            headers=self.headers,
            timeout=60,
        )

        try:
            body = response.json()
        except ValueError:
            body = response.text

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data dataset error "
                f"{response.status_code}: {body}"
            )

        # ---------------------------------------------------------
        # Bright Data may return the records directly as a list.
        # ---------------------------------------------------------
        if isinstance(body, list):
            return body

        if not isinstance(body, dict):
            raise RuntimeError(
                f"Unexpected Bright Data response type: {body}"
            )

        # ---------------------------------------------------------
        # Read status.
        # ---------------------------------------------------------
        status = str(
            body.get("status", "")
        ).strip().lower()

        # ---------------------------------------------------------
        # IMPORTANT:
        #
        # "collecting" / "running" / "pending" are NOT errors.
        # The collector is still working.
        # Return None so collect() can poll again.
        # ---------------------------------------------------------
        pending_statuses = {
            "collecting",
            "building",
            "running",
            "pending",
            "starting",
            "queued",
            "processing",
            "in_progress",
            "in-progress",
        }

        if status in pending_statuses:
            return None

        # ---------------------------------------------------------
        # Bright Data can also say:
        #
        # {"status": "collecting",
        #  "message": "Job is not finished"}
        #
        # Handle that safely.
        # ---------------------------------------------------------
        message = str(
            body.get("message", "")
        ).strip().lower()

        pending_messages = (
            "job is not finished",
            "not finished",
            "not ready",
            "still collecting",
            "in progress",
            "in-progress",
            "processing",
        )

        if any(
            phrase in message
            for phrase in pending_messages
        ):
            return None

        # ---------------------------------------------------------
        # Real failure states.
        # ---------------------------------------------------------
        failed_statuses = {
            "failed",
            "failure",
            "error",
            "cancelled",
            "canceled",
        }

        if status in failed_statuses:
            raise RuntimeError(
                f"Bright Data collection failed: {body}"
            )

        # ---------------------------------------------------------
        # Dataset may be returned under different keys.
        # ---------------------------------------------------------
        if isinstance(body.get("data"), list):
            return body["data"]

        if isinstance(body.get("results"), list):
            return body["results"]

        if isinstance(body.get("records"), list):
            return body["records"]

        # ---------------------------------------------------------
        # Empty dataset can be valid after completion.
        # If Bright Data explicitly says completed but gives no
        # records, return an empty list instead of treating it as
        # an API error.
        # ---------------------------------------------------------
        completed_statuses = {
            "completed",
            "complete",
            "finished",
            "ready",
            "done",
            "success",
            "succeeded",
        }

        if status in completed_statuses:
            return []

        # ---------------------------------------------------------
        # If Bright Data did not provide a status but the message
        # indicates that the job is still running, keep polling.
        # ---------------------------------------------------------
        if any(
            phrase in message
            for phrase in pending_messages
        ):
            return None

        raise RuntimeError(
            f"Bright Data returned unexpected dataset response: "
            f"{body}"
        )

    def collect(
        self,
        inputs: List[Dict[str, Any]],
        timeout: int = 600,
        poll_interval: int = 5,
    ) -> Tuple[List[Dict[str, Any]], str]:
        """
        Trigger a Bright Data collector and wait until its
        dataset is ready.

        The Bright Data collector is asynchronous, so this
        method polls until the data is available.
        """

        collection_id = self.trigger(inputs)

        start = time.time()
        attempt = 0

        while True:
            elapsed = time.time() - start

            if elapsed >= timeout:
                raise RuntimeError(
                    "Timed out waiting for Bright Data dataset. "
                    f"Collection ID: {collection_id}"
                )

            attempt += 1

            try:
                data = self.dataset(collection_id)

                # -------------------------------------------------
                # Dataset is ready.
                # -------------------------------------------------
                if isinstance(data, list):
                    return data, collection_id

            except RuntimeError as exc:
                error_text = str(exc).lower()

                # -------------------------------------------------
                # Some Bright Data responses may still raise an
                # error-like message while the job is collecting.
                # Treat these as retryable.
                # -------------------------------------------------
                retryable_messages = (
                    "job is not finished",
                    "not finished",
                    "not ready",
                    "still collecting",
                    "collecting",
                    "in progress",
                    "processing",
                )

                if not any(
                    phrase in error_text
                    for phrase in retryable_messages
                ):
                    # This is a real error.
                    raise

            # -----------------------------------------------------
            # Wait before polling Bright Data again.
            # -----------------------------------------------------
            remaining = timeout - (time.time() - start)

            if remaining <= 0:
                break

            sleep_time = min(
                poll_interval,
                max(1, int(remaining)),
            )

            time.sleep(sleep_time)

        raise RuntimeError(
            "Timed out waiting for Bright Data dataset. "
            f"Collection ID: {collection_id}"
        )

    def self_heal(
        self,
        prompt: str,
    ) -> Dict[str, Any]:
        """
        Ask Bright Data to refactor/self-heal the collector.
        """

        response = requests.post(
            f"{BASE_URL}/dca/collectors/"
            f"{self.collector}/refactor_template",
            headers=self.headers,
            json={
                "prompt": prompt,
            },
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = {
                "raw_response": response.text,
            }

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data Self-Healing error "
                f"{response.status_code}: {result}"
            )

        if isinstance(result, dict):
            return result

        return {
            "result": result,
        }

    def self_heal_progress(
        self,
    ) -> Dict[str, Any]:
        """
        Return the current Bright Data self-healing progress.
        """

        response = requests.get(
            f"{BASE_URL}/dca/collectors/"
            f"{self.collector}/refactor_template/progress",
            headers=self.headers,
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = {
                "raw_response": response.text,
            }

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data Self-Healing progress error "
                f"{response.status_code}: {result}"
            )

        if isinstance(result, dict):
            return result

        return {
            "result": result,
            }
