import os
import time
from typing import Any, Dict, List, Optional, Tuple

import requests


BASE_URL = "https://api.brightdata.com"


class BrightDataClient:
    """Client for Bright Data collector and self-healing APIs."""

    def __init__(self) -> None:
        self.token = os.getenv("BRIGHT_DATA_API_TOKEN")
        self.collector = os.getenv("BRIGHT_DATA_COLLECTOR_ID")

        if not self.token:
            raise RuntimeError(
                "BRIGHT_DATA_API_TOKEN is not set. "
                "Add it to Streamlit Secrets or your .env file."
            )

        if not self.collector:
            raise RuntimeError(
                "BRIGHT_DATA_COLLECTOR_ID is not set. "
                "Add it to Streamlit Secrets or your .env file."
            )

    @property
    def headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

    def trigger(self, inputs: List[Dict[str, Any]]) -> str:
        """Start a Bright Data collector run."""

        response = requests.post(
            f"{BASE_URL}/dca/trigger",
            params={
                "collector": self.collector,
                "queue_next": 1,
            },
            headers=self.headers,
            json=inputs,
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = response.text

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data trigger error "
                f"{response.status_code}: {result}"
            )

        if not isinstance(result, dict):
            raise RuntimeError(
                f"Unexpected Bright Data trigger response: {result}"
            )

        collection_id = result.get("collection_id")

        if not collection_id:
            raise RuntimeError(
                f"Bright Data did not return collection_id: {result}"
            )

        return str(collection_id)

    def dataset(self, snapshot_id: str) -> Optional[List[Dict[str, Any]]]:
        """Get the dataset generated by a collector run."""
def dataset(
    self,
    collection_id: str,
) -> Optional[List[Dict[str, Any]]]:
    """
    Fetch the dataset produced by a Bright Data collection.

    Returns:
        list: Dataset records when the job is finished.
        None: When the collection is still running.

    Raises:
        RuntimeError: When Bright Data reports a real failure.
    """

    response = requests.get(
        f"{BASE_URL}/datasets/{collection_id}",
        headers=self.headers,
        timeout=60,
    )

    try:
        body = response.json()
    except ValueError:
        body = {"raw_response": response.text}

    if response.status_code >= 400:
        raise RuntimeError(
            f"Bright Data dataset error "
            f"{response.status_code}: {body}"
        )

    if not isinstance(body, dict):
        raise RuntimeError(
            f"Unexpected Bright Data response type: {body}"
        )

    # ---------------------------------------------------------
    # Collection is still running.
    # Do NOT raise an error here.
    # collect() will poll again.
    # ---------------------------------------------------------
    status = str(body.get("status", "")).lower()

    if status in {
        "collecting",
        "running",
        "pending",
        "queued",
        "processing",
        "in_progress",
    }:
        return None

    # ---------------------------------------------------------
    # Bright Data explicitly reports failure.
    # ---------------------------------------------------------
    if status in {
        "failed",
        "error",
        "cancelled",
        "canceled",
    }:
        raise RuntimeError(
            f"Bright Data collection failed: {body}"
        )

    # ---------------------------------------------------------
    # Dataset records.
    # ---------------------------------------------------------
    if isinstance(body.get("results"), list):
        return body["results"]

    if isinstance(body.get("records"), list):
        return body["records"]

    # Some Bright Data responses can return the dataset
    # directly in a list.
    if isinstance(body, list):
        return body

    # ---------------------------------------------------------
    # If there is no status but the dataset is not ready yet,
    # keep polling when Bright Data indicates that explicitly.
    # ---------------------------------------------------------
    message = str(body.get("message", "")).lower()

    if any(
        word in message
        for word in [
            "not finished",
            "not ready",
            "still collecting",
            "in progress",
        ]
    ):
        return None

    raise RuntimeError(
        f"Bright Data returned unexpected dataset response: {body}"
    )


def collect(
    self,
    inputs: List[Dict[str, Any]],
    timeout: int = 600,
    poll_interval: int = 5,
) -> Tuple[List[Dict[str, Any]], str]:
    """
    Trigger a Bright Data collector and wait until the dataset
    is ready.

    The collector API is asynchronous, so this method polls
    until the job finishes or the timeout is reached.
    """

    collection_id = self.trigger(inputs)

    start = time.time()
    attempt = 0

    while time.time() - start < timeout:
        attempt += 1

        try:
            data = self.dataset(collection_id)

            # Dataset is ready.
            if isinstance(data, list):
                return data, collection_id

        except RuntimeError as exc:
            error_text = str(exc)

            # Handle the case where an older/alternate Bright Data
            # response reports "Job is not finished".
            if (
                "job is not finished" in error_text.lower()
                or "not finished" in error_text.lower()
                or "collecting" in error_text.lower()
            ):
                data = None
            else:
                # Real error — don't hide it.
                raise

        # Still collecting.
        elapsed = int(time.time() - start)
        remaining = max(0, timeout - elapsed)

        # Wait before checking again.
        time.sleep(
            min(poll_interval, remaining)
        )

    raise RuntimeError(
        "Timed out waiting for Bright Data dataset. "
        f"Collection ID: {collection_id}"
    )    def self_heal(self, prompt: str) -> Dict[str, Any]:
        """Ask Bright Data to refactor/self-heal the collector."""

        response = requests.post(
            f"{BASE_URL}/dca/collectors/"
            f"{self.collector}/refactor_template",
            headers=self.headers,
            json={"prompt": prompt},
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = {"raw_response": response.text}

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data Self-Healing error "
                f"{response.status_code}: {result}"
            )

        if isinstance(result, dict):
            return result

        return {"result": result}
    )
    def self_heal_progress(self) -> Dict[str, Any]:
        """Return the current Bright Data self-healing progress."""

        response = requests.get(
            f"{BASE_URL}/dca/collectors/"
            f"{self.collector}/refactor_template/progress",
            headers=self.headers,
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = {"raw_response": response.text}

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data Self-Healing progress error "
                f"{response.status_code}: {result}"
            )

        if isinstance(result, dict):
            return result

        return {"result": result}
