import os
import time
from typing import Any, Dict, List, Optional, Tuple

import requests


BASE_URL = "https://api.brightdata.com"


class BrightDataClient:
    """Client for Bright Data collector and self-healing APIs."""

    def __init__(self) -> None:
        self.token = os.getenv("BRIGHT_DATA_API_TOKEN")
        self.collector = os.getenv("BRIGHT_DATA_COLLECTOR_ID")

        if not self.token:
            raise RuntimeError(
                "BRIGHT_DATA_API_TOKEN is not set. "
                "Add it to Streamlit Secrets or your .env file."
            )

        if not self.collector:
            raise RuntimeError(
                "BRIGHT_DATA_COLLECTOR_ID is not set. "
                "Add it to Streamlit Secrets or your .env file."
            )

    @property
    def headers(self) -> Dict[str, str]:
        return {
            "Authorization": f"Bearer {self.token}",
            "Content-Type": "application/json",
        }

    def trigger(self, inputs: List[Dict[str, Any]]) -> str:
        """Start a Bright Data collector run."""

        response = requests.post(
            f"{BASE_URL}/dca/trigger",
            params={
                "collector": self.collector,
                "queue_next": 1,
            },
            headers=self.headers,
            json=inputs,
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = response.text

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data trigger error "
                f"{response.status_code}: {result}"
            )

        if not isinstance(result, dict):
            raise RuntimeError(
                f"Unexpected Bright Data trigger response: {result}"
            )

        collection_id = result.get("collection_id")

        if not collection_id:
            raise RuntimeError(
                f"Bright Data did not return collection_id: {result}"
            )

        return str(collection_id)

    def dataset(self, snapshot_id: str) -> Optional[List[Dict[str, Any]]]:
        """Get the dataset generated by a collector run."""

        response = requests.get(
            f"{BASE_URL}/dca/dataset",
            params={"id": snapshot_id},
            headers=self.headers,
            timeout=60,
        )

        try:
            body = response.json()
        except ValueError:
            body = response.text

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data dataset error "
                f"{response.status_code}: {body}"
            )

        if isinstance(body, list):
            return body

        if isinstance(body, dict):
            status = str(body.get("status", "")).lower()

            pending_statuses = {
                "building",
                "running",
                "pending",
                "starting",
                "queued",
            }

            if status in pending_statuses:
                return None

            if isinstance(body.get("data"), list):
                return body["data"]

            if isinstance(body.get("results"), list):
                return body["results"]

            if isinstance(body.get("records"), list):
                return body["records"]

            raise RuntimeError(
                f"Bright Data returned unexpected dataset response: {body}"
            )

        raise RuntimeError(
            f"Unexpected Bright Data response type: {body}"
        )

    def collect(
        self,
        inputs: List[Dict[str, Any]],
        timeout: int = 600,
        poll_interval: int = 10,
    ) -> Tuple[List[Dict[str, Any]], str]:
        """Trigger a collector and wait for its dataset."""

        collection_id = self.trigger(inputs)

        start = time.time()

        while time.time() - start < timeout:
            data = self.dataset(collection_id)

            if isinstance(data, list):
                return data, collection_id

            time.sleep(poll_interval)

        raise RuntimeError(
            "Timed out waiting for Bright Data dataset. "
            f"Collection ID: {collection_id}"
        )

    def self_heal(self, prompt: str) -> Dict[str, Any]:
        """Ask Bright Data to refactor/self-heal the collector."""

        response = requests.post(
            f"{BASE_URL}/dca/collectors/"
            f"{self.collector}/refactor_template",
            headers=self.headers,
            json={"prompt": prompt},
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = {"raw_response": response.text}

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data Self-Healing error "
                f"{response.status_code}: {result}"
            )

        if isinstance(result, dict):
            return result

        return {"result": result}

    def self_heal_progress(self) -> Dict[str, Any]:
        """Return the current Bright Data self-healing progress."""

        response = requests.get(
            f"{BASE_URL}/dca/collectors/"
            f"{self.collector}/refactor_template/progress",
            headers=self.headers,
            timeout=60,
        )

        try:
            result = response.json()
        except ValueError:
            result = {"raw_response": response.text}

        if response.status_code >= 400:
            raise RuntimeError(
                f"Bright Data Self-Healing progress error "
                f"{response.status_code}: {result}"
            )

        if isinstance(result, dict):
            return result

        return {"result": result}
